# Generated by Django 3.1 on 2020-10-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_firebase_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
